export const defaultSkin = {
  colors: {
    primary: '#09090b',
    secondary: '#fafafa',
    accent: '#16a34a',
    card: '#ffffff',
    cardForeground: '#09090b',
    popover: '#ffffff',
    popoverForeground: '#09090b',
    primaryForeground: '#fafafa',
    secondaryForeground: '#09090b',
    muted: '#f4f4f5',
    mutedForeground: '#71717a',
    accentForeground: '#fafafa',
    destructive: '#ef4444',
    destructiveForeground: '#fafafa',
    border: '#e4e4e7',
    input: '#e4e4e7',
    ring: '#09090b',
  },
  logo_url: '/placeholder-logo.svg',
  font_family: 'Inter, sans-serif',
  hero_image_url: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=800&dpr=2&q=80',
  hero_title: 'Your Brand Here',
  hero_subtitle: 'Discover a new way of doing things.',
  cta_text: 'Get Started Now',
  metadata: {
    title: 'Default Storefront',
    description: 'The default description for your storefront.',
  },
};
